Dynatrace/superdump

- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Controllers/InputModel.cs
- src/SuperDumpService/Controllers/api/DumpsController.cs
accidentally changed a field-name in the API, thus broke it. he name.
> fix breaking change in api

- build/runsuperdump.cmd
- conf/appsettings.json
- src/SuperDumpService/Helpers/PathHelper.cs
- src/SuperDumpService/Properties/PublishProfiles/publish-profile.pubxml
- src/SuperDumpService/Services/BundleStorageFilebased.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpService.csproj
In order to make SuperDumpService run under linux, I did this:
* change hangfire-storage to in-memory (optionally)
* include "linux-64" in RuntimeIdentifiers
* fix a few path related problems
What's not working:
* Dump-download via api did not quite work yet.
* The whole analysis of course. This will be a larger project...
> Make superdumpservice start up under linux (first step)

- conf/appsettings.json
- src/SuperDump.sln
- src/SuperDump/Program.cs
- src/SuperDump/SuperDump.csproj
- src/SuperDumpSelector/Program.cs
- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Helpers/PathHelper.cs
- src/SuperDumpService/Helpers/ProcessRunner.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Models/DumpMetainfo.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/DownloadService.cs
- src/SuperDumpService/Services/DumpRepository.cs
- src/SuperDumpService/Services/DumpStorageFilebased.cs
- src/SuperDumpService/Services/SuperDumpRepository.cs
- src/SuperDumpService/Services/UnpackService.cs
- src/SuperDumpService/SuperDumpService.csproj
- src/SuperDumpService/SuperDumpSettings.cs
- src/SuperDumpService/ViewModels/FileViewModel.cs
- src/SuperDumpService/ViewModels/ReportViewModel.cs
- src/SuperDumpService/Views/Home/Report.cshtml
- src/SuperDumpService/Views/Home/_File.cshtml
- src/SuperDumpService/wwwroot/css/site.css
- src/SuperDumpTests/SuperDumpTests.csproj
Big preparation step for linux coredump support:
* `.core.gz` now trigger an analysis just like windows `.dmp` files.
* when uploading a `zip` file, the files that are located in the same directory as a dump, are now added to the report (if setting *"IncludeOtherFilesInReport"* is true). The reason is:
** Our automated linux crashdumps, contain an additional library next to the core.gz file, which is called libs.tar.gz and contains all the linux libs, that are necessary for solid analysis.
** Also our automated windows crashdumps contain some additional files, which are usually interesting. Adding them to SuperDump just makes it more convenient.
* renamed some output-files: 
** dumps now keep their original name
** results are not named after the DumpId anymore, but have speaking names
* …
> Coredump support

- src/SuperDumpService/Services/DumpStorageFilebased.cs
due to a glitch with re-running analysis, file-entries might be added multiple times. shouldn't happen too often, so made the easy fix to just accept that (and take the first file)
> fix error with multiple files in metainfo

- conf/appsettings.json
- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/DumpStorageFilebased.cs
- src/SuperDumpService/SuperDumpSettings.cs
- src/SuperDumpService/Webterm/WebTermHandler.cs
Makes it easier to invoke linux coredump analysis scripts, by adding new command template arguments.
```
{dumppath}: full path to primary dump file
{dumpname}: filename of primary dump file
{dumpdir}: path to directory which contains the primary dump file
{outputpath}: full path to output json file
{outputname}: filename of output json file
```
It's possible to use Docker f. Windows and Hyper-V to invoke Linux dump analysis scripts. These scripts are not yet part of this repository though.
> extended command templates.

- build/conf/appsettings.json
- src/SuperDump/Program.cs
- src/SuperDumpSelector/Program.cs
We actually just need a non-zero exit code in case analysis failed for some reason. No need to let it crash via unhandled exception.
> don't let superdump.exe and superdumpselector.exe crash in case of errors

- src/SuperDump/Program.cs
because exceptions were swallowed previously, leading to confusing messages. see https://github.com/Dynatrace/superdump/issues/52
> improve exception handling in LoadDump

- src/LibunwindWrapper/LibunwindWrapper.cpp
- src/LibunwindWrapper/LibunwindWrapper.h
- src/LibunwindWrapper/Main.cpp
- src/LibunwindWrapper/Main.h
- src/SuperDump.Analyzer.Linux/Analysis/UnwindAnalyzer.cs
The old approach with AUXV failed for dumps from 32 bit systems
> extract process architecture directly from ELF header

- src/SuperDump.Analyzer.Linux/Analysis/CoreDumpAnalyzer.cs
- src/SuperDump.Analyzer.Linux/Analysis/GdbAnalyzer.cs
- src/SuperDump.Analyzer.Linux/Analysis/SharedLibAnalyzer.cs
- src/SuperDump.Analyzer.Linux/Program.cs
- src/SuperDump.Common/LinuxAnalyzerExitCode.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Views/Home/_Summary.cshtml
- src/SuperDumpService/Views/Home/_Threads.cshtml
Fixed:
- Old coredump analysis results cannot be displayed
- GDB analysis gets stuck on dumps with lots of threads
- No results are written for coredumps that don't contain the NT_FILE note (older kernels did not write this note). With this patch, the linux analysis exit code describes the error that happened.
> Linux analysis bugfixes

- building/build.cmd
- building/msbuild.targets
Support building with and without linux (i.e. docker) as part of build arguments
"building/build.cmd" will perform a windows only build (i'm assuming people
running this system are likely to be windows orientated
"building/build.cmd linux" specifies target to include the docker components
> Support windows only and linux builds

- src/SuperDump/Analyzers/WinDbgAnalyzer.cs
- src/SuperDump/Program.cs
This also fixes the fact uext.dll seems to have moved from winxp->winext
in latest debugging tools
(P.S. I'm not sure i've got linefeeds correct on these PR's! Using git
for both linux+windows dev)
> Search Environment paths for extensions.

- building/build.cmd
Allow Visual studio enterprise to be used as build environment by making
use of the %VSINSTALLDIR% environment variable instead of hard coding
the path to visual studio
> Allow Visual studio enterprise to be used as build environment 

- src/SuperDump.Analyzer.Linux/Analysis/DebugSymbolResolver.cs
We strip the "lib" prefix for our NodeJs extensions after build therefore downloading of the .dbg file fails currently as the dbg file has still the lib prefix. Therefore the missing "lib" prefix should be added to allow superdump to download the correct file.
> Add leading "lib" prefix for NodeJs extensions

- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Controllers/LoginController.cs
- src/SuperDumpService/Controllers/SimilarityController.cs
- src/SuperDumpService/Helpers/LdapCookieAuthenticationExtension.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/Views/Home/Create.cshtml
- src/SuperDumpService/wwwroot/js/site.js
Use CookieSecurePolicy.Always to avoid sending the authentication cookie when not using https. The antiforgery token is now also validated in relevant controllers to avoid Cross Site Request Forgery.
> add cookie security flag and antiforgery validation

- README.md
- build/runsuperdump.cmd
- conf/appsettings.json
- src/SuperDumpService/Controllers/LoginController.cs
- src/SuperDumpService/ViewModels/LoginViewModel.cs
- src/SuperDumpService/Views/Login/Login.cshtml
Added a different login message if the credentials are correct but the user isn't in a SuperDump group. Added a https example url to ASPNETCORE_URLS and updated the authorization section in the README.md to show that requirement.
> improve failed login alert messages and setup documentation

- conf/appsettings.json.template
- src/SuperDumpService/Controllers/AdminController.cs
- src/SuperDumpService/Controllers/api/DumpsController.cs
- src/SuperDumpService/Helpers/LocalDBAccess.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Program.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/ElasticSearchService.cs
- src/SuperDumpService/Services/RelationshipRepository.cs
- src/SuperDumpService/Services/SimilarityService.cs
- src/SuperDumpService/Services/SuperDumpRepository.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpSettings.cs
We've encountered a number of nasty deadlocks, which only happened after a few days, mostly under very high load. The deadlock manifested by stuck transactions on "Overview" and "Result" requests and it turned out hundreds of threads were stuck in waiting for Semaphores/WaitHandles/ManualResetEvents in System.Threading/Task namespaces.
Here are all stacks: https://gist.github.com/discostu105/adb41868e60157edc7b8fa454bc2873d
The most suspicious one:
[GCFrame: 0000006339e7db90] 
[HelperMethodFrame_1OBJ: 0000006339e7dcd8] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) …
> Hangfire deadlock fix

- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Helpers/PathHelper.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/BundleStorageFilebased.cs
- src/SuperDumpService/Services/DumpRepository.cs
- src/SuperDumpService/Services/DumpRetentionService.cs
- src/SuperDumpService/Services/DumpStorageFilebased.cs
- src/SuperDumpService/Services/ElasticSDResult.cs
- src/SuperDumpService/Services/ElasticSearchService.cs
- src/SuperDumpService/Services/IDumpStorage.cs
- src/SuperDumpService/Services/IRelationshipStorage.cs
- src/SuperDumpService/Services/RelationshipRepository.cs
- src/SuperDumpService/Services/RelationshipStorageFilebased.cs
- src/SuperDumpService/Services/SlackNotificationService.cs
- src/SuperDumpService/Services/SuperDumpRepository.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/TagHelpers/InteractiveLinkTagHelper.cs
- src/SuperDumpService/ViewModels/FileViewModel.cs
- src/SuperDumpService/ViewModels/InteractiveViewModel.cs
- src/SuperDumpService/ViewModels/ReportViewModel.cs
- src/SuperDumpService/Views/Home/Interactive.cshtml
- src/SuperDumpService/Views/Home/Report.cshtml
- src/SuperDumpService/Views/Home/Rerun.cshtml
- src/SuperDumpService/Views/Home/_File.cshtml
- src/SuperDumpService/Views/Home/_Memory.cshtml
- src/SuperDumpService/Webterm/WebTermHandler.cs
* Use DumpIdentifier in all APIs. This implifies a lot of code.
* Reduce dependencies. Created interfaces for a few classes to make abstraction in tests easier.
> Some cleanups

- src/SuperDumpService.Benchmark/Benchmarks/MiniInfoBenchmarks.cs
- src/SuperDumpService.Benchmark/Benchmarks/SimilarityCalculationBenchmarks.cs
- src/SuperDumpService.Benchmark/Benchmarks/SimilarityServiceBenchmarks.cs
- src/SuperDumpService.Benchmark/Fakes/FakeDumpStorage.cs
- src/SuperDumpService.Benchmark/Program.cs
- src/SuperDumpService/Controllers/AdminController.cs
- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Controllers/SimilarityController.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Models/CrashSimilarity.cs
- src/SuperDumpService/Models/DumpIdentifier.cs
- src/SuperDumpService/Models/DumpMetainfo.cs
- src/SuperDumpService/Models/DumpMiniInfo.cs
- src/SuperDumpService/Services/DumpStorageFilebased.cs
- src/SuperDumpService/Services/RelationshipRepository.cs
- src/SuperDumpService/Services/RelationshipStorageFilebased.cs
- src/SuperDumpService/Services/SimilarityService.cs
- src/SuperDumpService/SuperDumpService.csproj
* Changed MiniInfo to only contain hashes, instead of strings to save memory.
* DumpIdentifier objects are now pooled. Especially in RelationshipRepository, the same DumpIdentifier would be used a number of times.
> reduce memory consumption

- src/SuperDump.sln
- src/SuperDumpService.Benchmark/SuperDumpService.Benchmark.csproj
- src/SuperDumpService.Test.Fakes/FakeDumpStorage.cs
- src/SuperDumpService.Test.Fakes/FakeRelationshipStorage.cs
- src/SuperDumpService.Test.Fakes/SuperDumpService.Test.Fakes.csproj
- src/SuperDumpService.Test/SlackNotificationTests.cs
- src/SuperDumpService.Test/SuperDumpService.Test.csproj
- src/SuperDumpService/Services/SlackNotificationService.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpService.csproj
* added a unit test for slacknotificationservice
* added asp.net core healthchecks
The reason behind this is, we got some weird exceptions like these
```
Slack notifications failed: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNetCore.Diagnostics.HealthChecks'
at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
at …
```
> Slacknotificationservice tests

- src/SuperDumpSelector/SuperDumpSelector.csproj
- src/SuperDumpService.Test.Fakes/FakeDumpStorage.cs
- src/SuperDumpService.Test.Fakes/FakeJiraApiService.cs
- src/SuperDumpService.Test/JiraIssueRepositoryTest.cs
- src/SuperDumpService/JiraIntegrationSettings.cs
- src/SuperDumpService/Models/DumpIdentifier.cs
- src/SuperDumpService/Services/JiraApiService.cs
- src/SuperDumpService/Services/JiraIssueRepository.cs
* jira authentication now uses cookies to keep sessionid. this is to avoid login for every jira-rest-call. saves LDAP a bunch of work.
* fixed buggy handling when jira issues disappear. improved unit tests.
> JIRA rest api session handling and bugfixes

- src/SuperDump.DebugDiag/App.config
- src/SuperDump.DebugDiag/Options.cs
- src/SuperDump.DebugDiag/Program.cs
- src/SuperDump.DebugDiag/SuperDump.DebugDiag.csproj
- src/SuperDump/Options.cs
- src/SuperDump/Program.cs
- src/SuperDump/SuperDump.csproj
- src/SuperDumpSelector/App.config
- src/SuperDumpSelector/Options.cs
- src/SuperDumpSelector/Program.cs
- src/SuperDumpSelector/SuperDumpSelector.csproj
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpService.csproj
Use the Dynatrace "Remote Call" tracing capability to monitor execution of analysis in child processes. This isn't perfectly "used as intended", but to a wider extent, invoking a child-process and get a result back might be considered a "remote call" :).
> Add Dynatrace SDK to trace child process activations

- src/SuperDumpService/Services/AnalysisService.cs
Add a check if the primary dump file is empty before starting the dump analysis to avoid an misleading exception text.
> add check if primary dump is empty to AnalysisService

- src/SuperDumpService.Test.Fakes/FakeDumpStorage.cs
- src/SuperDumpService/Services/DumpRepository.cs
- src/SuperDumpService/Services/DumpStorageFilebased.cs
- src/SuperDumpService/Services/IDumpStorage.cs
fix bug that the DumpMetainfo file is read multiple times during the repository population
> Improve IsPrimaryDumpAvailable() Performance

- src/SuperDump/SuperDump.csproj
It was possible for the 32bit Dump analysis to fail because of insufficient memory. Added the LargeAddressAware flag to mitigate this issue
> add LargeAddressAware Flag to the 32bit version of SuperDump

- src/SuperDumpService.Test/JiraIssueRepositoryTest.cs
this unit test was flawed, because it relied on the order of elements in a dictionary, which isn't deterministic
> Fix flawed unit test

- src/SuperDumpService/Controllers/HomeController.cs
Since the update to .NET core 3.0 preview 6 the request limit setting in the web.config seems not to work anymore.
Added the [RequestSizeLimit] attribute to the Upload method to allow the upload of large dumps.
> add [RequestSizeLimit] attribute to the Upload method

- src/SuperDumpService.Test/JiraIssueRepositoryTest.cs
- src/SuperDumpService/Models/JiraIssueModel.cs
- src/SuperDumpService/Services/JiraIssueRepository.cs
* Fixed a bug that would prevent the cached Jira issues from being updated if one issue references multiple bundles.
* Added an unit test for the Jira issue refresh method.
> Fix Jira issue refresh

- src/SuperDump/SuperDump.csproj
Since ClrMD version 1.0.5 there seems to be an issue with cache* elements in the symbol path. 
I reverted the update for now.
> Revert ClrMD back to version 1.0.3

- src/SuperDump.Common/DynatraceSourceLink.cs
- src/SuperDumpService.Test/SvnLinkParserTests.cs
Added handling for another source path format.
However, the source links are still not working since we do not have information about the correct case of the filename.
> fix svn source links

- src/SuperDump.Analyzer.Linux/Analysis/CoreDumpAnalyzer.cs
- src/SuperDump.Analyzer.Linux/Analysis/ElfHeaderAnalyzer.cs
The linux dump analysis now parses the header information from readelf for better system architecture detection.
> Add elf header analyzer

- conf/appsettings.json.template
- src/SuperDumpService/Services/DownloadService.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpService.csproj
- src/SuperDumpService/SuperDumpSettings.cs
The dump Download from an URL fails sometimes. Now the Download is attempted multiple times if it fails. The maximum number of retry attempts can be configured in the appsettings.json file.
> add retry for dump downloads using the DownloadService

- conf/appsettings.json.template
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpSettings.cs
The default timeout of the HttpClient is 100 seconds. It is possible that this is not sufficient for larger dump files.
I added a field for the timeout to the appsettings and increased the default to 4 minutes.
> increase timeout of HttpClient

- src/SuperDump.Analyzer.Linux/Dockerfile.Linux
In the fix for the "rsync file vanished" error I used syntax that only works in /bin/bash. However, the command for the analysis is executed using /bin/sh.
This change should fix that problem.
> fix linux analysis command

- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/Analyzers/DumpAnalyzerJob.cs
- src/SuperDumpService/Services/Analyzers/ElasticSearchJob.cs
- src/SuperDumpService/Services/DumpRepository.cs
- src/SuperDumpService/Views/Home/_System.cshtml
Fixed that the error message was not reset when rerunning an analysis.
Now the Dump Analyzer does not change the pipeline state to failed if the dump is not a Linux or Windows dump since it does nothing in that case.
The Elastic Search Analyzer now only starts if the previous state is succeeded.
> fix rerun analysis and analysis pipeline state

- conf/appsettings.json.template
- src/SuperDumpService/AmazonSqsSettings.cs
- src/SuperDumpService/Controllers/api/DumpsController.cs
- src/SuperDumpService/Helpers/SuperDumpLogExtension.cs
- src/SuperDumpService/Models/DumpAnalysisResponse.cs
- src/SuperDumpService/Models/InputModel.cs
- src/SuperDumpService/Services/AmazonSqsService.cs
- src/SuperDumpService/Services/SuperDumpRepository.cs
- src/SuperDumpService/Startup.cs
- src/SuperDumpService/SuperDumpService.csproj
- src/SuperDumpService/SuperDumpSettings.cs
This PR adds support for Amazon SQS Queues.
The SuperDump service now checks periodically if a new message is in the input queue. After starting an analysis a link to the dump is sent to an output queue.
> Add amazon sqs support

- src/SuperDumpService/Helpers/SuperDumpLogExtension.cs
- src/SuperDumpService/Services/JiraApiService.cs
- src/SuperDumpService/Services/SuperDumpRepository.cs
- src/SuperDumpService/Services/UnpackService.cs
This PR fixes the problem that the whole analysis stops if an inner archive can't be opened/is corrupt.
Additionally, added a missing null check to the JiraApiService.
> Fix archive extraction error handling

- src/SuperDumpService/Models/DumpAnalysisResponse.cs
Changed the json property names of the dump analysis response for the Amazon SQS queue to lower case.
> change dump analysis response json property names to lower case

- src/SuperDumpService/Helpers/SuperDumpLogExtension.cs
- src/SuperDumpService/Services/DownloadService.cs
Added additional information to the log if a bundle download fails. The logging api is now used in this case instead of Console.WriteLine.
> improve download service logging

- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/Analyzers/AnalyzerJob.cs
- src/SuperDumpService/Services/Analyzers/AnalyzerPipeline.cs
- src/SuperDumpService/Services/Analyzers/ElasticSearchJob.cs
- src/SuperDumpService/Services/Analyzers/SimilarityAnalyzerJob.cs
The similarity detection did not work since the analysis service rework, since there is a check in the similarity analysis if the dump status is finished. However, this was only set after all analysis steps were finished, including the similarity analysis.
This PR adds post analysis steps, that are executed after the dump status was set correctly.
> Fix Similarity Detection

- src/SuperDumpService/Services/DumpRetentionService.cs
With this change, dump files that end with ".DMP" should also be deleted after the retention time.
> ignore case of file extension for dump retention

- src/SuperDumpService.Test/FaultReportingTests.cs
- src/SuperDumpService/AmazonSqsSettings.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Models/CrashSimilarity.cs
- src/SuperDumpService/Models/InputModel.cs
- src/SuperDumpService/Services/AmazonSqsClientService.cs
- src/SuperDumpService/Services/AmazonSqsFaultReportingSender.cs
- src/SuperDumpService/Services/AmazonSqsPollingService.cs
- src/SuperDumpService/Services/AmazonSqsService.cs
- src/SuperDumpService/Services/AnalysisService.cs
- src/SuperDumpService/Services/Analyzers/AnalyzerJob.cs
- src/SuperDumpService/Services/Analyzers/AnalyzerPipeline.cs
- src/SuperDumpService/Services/Analyzers/ElasticSearchJob.cs
- src/SuperDumpService/Services/Analyzers/FaultReportJob.cs
- src/SuperDumpService/Services/Analyzers/SimilarityAnalyzerJob.cs
- src/SuperDumpService/Services/FaultReportingService.cs
- src/SuperDumpService/Services/IFaultReportSender.cs
- src/SuperDumpService/Startup.cs
With this feature, SuperDump can report the result of a dump analysis as a message to a queue. Currently only Amazon SQS is implemented.
The goal is that another system can use this qualified analysis to display more information and possibly use it to for deduplication.
> Fault Reporting

- src/SuperDumpService/Controllers/HomeController.cs
- src/SuperDumpService/Helpers/Utility.cs
- src/SuperDumpService/Models/DumpIdentifier.cs
- src/SuperDumpService/Services/SlackNotificationService.cs
- src/SuperDumpService/Views/Home/BundleCreated.cshtml
- src/SuperDumpService/Views/Home/Dumps.cshtml
- src/SuperDumpService/Views/Home/Interactive.cshtml
- src/SuperDumpService/Views/Home/Report.cshtml
- src/SuperDumpService/Views/Home/Rerun.cshtml
- src/SuperDumpService/Views/Home/_DumpList.cshtml
- src/SuperDumpService/Views/Similarity/CompareDumps.cshtml
Uri simplification for convenience.
Show dump:
old: http://localhost:5000/Home/Report?bundleId=lze0821&dumpId=gtc0647
new: http://localhost:5000/Home/Dump?id=lze0821:gtc0647
It's shorter and the dump identifier is easier to copy. The old URI still works.
> Simplify uris

- building/build.cmd
- src/SuperDump.Analyzer.Linux/SuperDump.Analyzer.Linux.csproj
Changes the MSBuild path back to the Visual Studio Professional path instead of Preview.
Also fixes a package downgrade build error
> Change Visual Studio version back to professional
