Dynatrace/superdump

conf/appsettings.json
src/SuperDumpService/Helpers/LocalDBAccess.cs
src/SuperDumpService/Startup.cs

Changed LocalDBAccess to make use of ConnectionStrings specified in Config File

Make Hangfire not use hardcoded ConnectionString

---

conf/appsettings.json
src/SuperDumpService/Models/SDFileInfo.cs
src/SuperDumpService/Services/AnalysisService.cs
src/SuperDumpService/Services/DumpStorageFilebased.cs
src/SuperDumpService/Startup.cs
src/SuperDumpService/SuperDumpSettings.cs
src/SuperDumpService/Views/Home/Create.cshtml
src/SuperDumpService/Views/Home/Report.cshtml

it's now configurable if a dump can be downloaded and be deleted after analysis. useful for cloud deployment with limited resources.

Configuration

---

src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/Controllers/InputModel.cs
src/SuperDumpService/Services/BundleRepository.cs
src/SuperDumpService/Views/Home/Create.cshtml
src/SuperDumpService/wwwroot/js/site.js

This makes it possible to add arbitrary attributes to a dump. E.g. Customer Name. Also renamed "jiraIssue" to "ref" custom property.

Add "custom properties" to API and GUI.

---

src/SuperDumpService/Models/DumpMetainfo.cs
src/SuperDumpService/Services/DumpStorageFilebased.cs
src/SuperDumpService/Services/SuperDumpRepository.cs
src/SuperDumpService/Views/Home/Report.cshtml

* "rerun" now does only delete result and log files, but no original "sibling" files. 
* also when uploading a zip with multiple dumps in the same directory, they are now not added multiple times.

Rerun improvements

---

src/SuperDumpService/Webterm/ConsoleAppManager.cs

eg. if process has target process has terminated in the meantime
fixes https://github.com/Dynatrace/superdump/issues/39

catch unhandled exceptions when reading or writing from stdin/out

---

src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/ViewModels/InteractiveViewModel.cs
src/SuperDumpService/Views/Home/_Threads.cshtml
src/SuperDumpService/Webterm/WebTermHandler.cs
src/SuperDumpService/wwwroot/js/webterm.js

* added possibility to add a command to interactive mode per url
* created links for "disassembling" instructions, which link directly into interactive mode

Disassembly link into interactive mode

---

build/conf/appsettings.json
conf/appsettings.json
src/SuperDumpService/Helpers/LocalDBAccess.cs
src/SuperDumpService/Services/AnalysisService.cs
src/SuperDumpService/Webterm/WebTermHandler.cs
src/SuperDumpService/web.config

* added possiblity to have bundleid and dumpid in linux command pattern
* minor fix for creating a localdb database freshly.

added possiblity to have bundleid and dumpid in linux command pattern

---

src/SuperDump/ModelHelpers/ModelHelpers.cs
src/SuperDumpService/Views/Home/_StacktracePlain.cshtml
src/SuperDumpService/Views/Home/_Summary.cshtml
src/SuperDumpService/Views/Home/_Threads.cshtml

* fixed NRE in CLRStracktrace to Model.
* fixed bug, that exception stacktrace was not correctly copied

Bugfixes around detecting CLR Stacktraces

---

src/SuperDump/Analyzers/WinDbgAnalyzer.cs
src/SuperDump/Program.cs
src/SuperDumpModels/SuperDumpModels.csproj
src/SuperDumpService/Views/Home/_Summary.cshtml

protect against:
* access violations in debugControl.Execute (WinDbgAnalyzer)
* Non-existing thread-id in LastEvent

Robustification

---

src/SuperDump/Analyzers/WindowsTagAnalyzer.cs
src/SuperDumpModels/SDTag.cs
src/SuperDumpService/wwwroot/css/site.css

I've added a tag for bad_alloc frames

Add tag for bad_alloc frames

---

src/SuperDumpService/Services/LdapAuthenticationService.cs

The SuperDump group of a user is now correctly determined if the user is in a child group.

fix determining in which group the user is

---

src/SuperDumpService/Services/LdapAuthenticationService.cs

Implemented a recursive group search instead of using GetAuthorizationGroups() because of performance issues and problems with accessing the group name of some of the returned groups.

fix recursive user group check

---

src/SuperDumpService/Services/LdapAuthenticationService.cs

The recursive user group check now uses the ldap service user correctly.

 fix ldap service user authentication

---

src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/Services/JiraIssueRepository.cs
src/SuperDumpService/Startup.cs

Fixed a bug that could insert null into the jira issue list. 
Added a check if the jira integration is enabled to avoid unnecessary method calls.
Added logging when the parsing of a jira-issues file of a bundle fails.

fix jira issue status refresh

---

src/SuperDumpService/Controllers/AdminController.cs
src/SuperDumpService/Controllers/SimilarityController.cs
src/SuperDumpService/Services/JiraIssueRepository.cs
src/SuperDumpService/Views/Similarity/CompareDumps.cshtml

Moved CompareDumps back to the SimilarityController.
Fixed bug at getting jira issues for similar dumps.

move CompareDumps back to the SimilarityController, fix bug 

---

src/SuperDumpService/Services/RelationshipRepository.cs

similarities are now read in parallel at startup.

speedup for population of relationship repository

---

conf/appsettings.json.template
src/SuperDumpService.Benchmark/Benchmarks/SimilarityServiceBenchmarks.cs
src/SuperDumpService.Test/JiraIssueRepositoryTest.cs
src/SuperDumpService.Test/SlackNotificationTests.cs
src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/Models/DumpMetainfo.cs
src/SuperDumpService/Services/DumpRepository.cs
src/SuperDumpService/Services/DumpRetentionService.cs
src/SuperDumpService/Services/DumpStorageFilebased.cs
src/SuperDumpService/Services/SearchService.cs
src/SuperDumpService/Services/SuperDumpRepository.cs
src/SuperDumpService/SuperDumpSettings.cs
src/SuperDumpService/ViewModels/DumpViewModel.cs
src/SuperDumpService/ViewModels/DumpsViewModel.cs
src/SuperDumpService/ViewModels/ReportViewModel.cs
src/SuperDumpService/ViewModels/RetentionViewModel.cs
src/SuperDumpService/Views/Home/Report.cshtml
src/SuperDumpService/Views/Home/_DumpList.cshtml
src/SuperDumpService/Views/Home/_RetentionTime.cshtml

Added a UI field that shows the remaining dump retention time and a button that extends the dump retention time.

Dump retention time

---

conf/appsettings.json.template
src/SuperDumpService.Benchmark/Benchmarks/SearchServiceBenchmarks.cs
src/SuperDumpService.Test.Fakes/FakeDumpStorage.cs
src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/JiraIntegrationSettings.cs
src/SuperDumpService/Models/DumpIdentifier.cs
src/SuperDumpService/Models/DumpMetainfo.cs
src/SuperDumpService/Models/JiraIssueModel.cs
src/SuperDumpService/Services/DumpRepository.cs
src/SuperDumpService/Services/DumpRetentionService.cs
src/SuperDumpService/Services/DumpStorageFilebased.cs
src/SuperDumpService/Services/IDumpStorage.cs
src/SuperDumpService/Services/JiraIssueRepository.cs
src/SuperDumpService/Services/SearchService.cs
src/SuperDumpService/ViewModels/RetentionViewModel.cs
src/SuperDumpService/Views/Home/_JiraIssues.cshtml
src/SuperDumpService/Views/Home/_RetentionTime.cshtml

The dump retention time is now extended if there is an open Jira issue for that bundle.

Jira Integration for Dump Retention Time

---

src/SuperDumpService.Benchmark/SuperDumpService.Benchmark.csproj
src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/Startup.cs
src/SuperDumpService/SuperDumpService.csproj
src/SuperDumpService/ViewModels/DumpsViewModel.cs
src/SuperDumpService/Views/Home/_DumpList.cshtml
src/SuperDumpService/Views/_ViewImports.cshtml

Fixed the pagination in the DumpList view, which did not work after the .net 3.0 update.
Additionally, there were dependency issues in in the Benchmark project.

Fix pagination

---

src/SuperDumpService/Models/JiraSearchQuery.cs
src/SuperDumpService/Models/JiraSearchResultModel.cs
src/SuperDumpService/Services/JiraApiService.cs
src/SuperDumpService/Services/JiraIssueRepository.cs

* Add handling for Jira search query  maxResults
* Add check to avoid exception if an issue is not returned by the refresh query anymore

Fix Jira issue refresh

---

src/SuperDumpService/Controllers/HomeController.cs
src/SuperDumpService/Controllers/api/DumpsController.cs
src/SuperDumpService/Helpers/SuperDumpLogExtension.cs
src/SuperDumpService/Helpers/TempFileHandle.cs
src/SuperDumpService/Helpers/Utility.cs
src/SuperDumpService/Models/BundleMetainfo.cs
src/SuperDumpService/Services/BundleRepository.cs
src/SuperDumpService/Services/DownloadService.cs
src/SuperDumpService/Services/SuperDumpRepository.cs

Added an API for directly uploading a file.

Direct file upload api

---

src/SuperDumpService/Services/DownloadService.cs

Add EnsureSuccessStatusCode call to avoid running into problems when processing the response.

add EnsureSuccessStatusCode call to DownloadService

---

src/SuperDumpService/Models/DumpMetainfo.cs
src/SuperDumpService/Services/AnalysisService.cs
src/SuperDumpService/Services/Analyzers/AnalyzerJob.cs
src/SuperDumpService/Services/Analyzers/AnalyzerPipeline.cs
src/SuperDumpService/Services/Analyzers/DumpAnalyzerJob.cs
src/SuperDumpService/Services/Analyzers/ElasticSearchJob.cs
src/SuperDumpService/Services/Analyzers/EmptyAnalyzerJob.cs
src/SuperDumpService/Services/Analyzers/SimilarityAnalyzerJob.cs
src/SuperDumpService/Services/BundleRepository.cs
src/SuperDumpService/Services/DumpRepository.cs
src/SuperDumpService/Services/SimilarityService.cs
src/SuperDumpService/Services/SuperDumpRepository.cs
src/SuperDumpService/Services/UnpackService.cs
src/SuperDumpService/Startup.cs
src/SuperDumpService/Views/Home/BundleCreated.cshtml
src/SuperDumpService/Views/Home/Report.cshtml
src/SuperDumpService/Views/Home/_DumpList.cshtml

This PR splits the analysis in multiple classes. This is to allow easier extension of the analysis process.
For uploaded archives that do not contain a known dump file, all files are shown as additional files in the report.

Rework analysis service

---

src/SuperDump.Analyzer.Linux/Analysis/DebugSymbolAnalysis.cs

Linux dump symbols were often not resolved correctly for the main executable because we did not subtract the module start address from the instruction pointer before passing it to the addr2line tool in that case. This is a problem if the main module does not start at 0.
Additionally, we handle individual module segments as modules in our internal data structure. However, the addr2line tool expects an offset relative to the start of the whole module. 
Now the module start address is calculated by subtracting the page offset multiplied by the page size from the segment start address.

fix linux symbol resolving

---

LICENSE
README.md
src/SuperDump/CombinedStackFrame.cs
src/SuperDump/CombinedStackTrace.cs

This has been long overdue. Wink to @goldshtn. Thank you :)
fixes #202

Add license attribution for msos

---

conf/appsettings.json.template
src/SuperDump.DebugDiag/SuperDump.DebugDiag.csproj
src/SuperDump.sln
src/SuperDump/SuperDump.csproj
src/SuperDumpModels/SuperDumpModels.csproj
src/SuperDumpSelector/SuperDumpSelector.csproj
src/SuperDumpService.Benchmark/SuperDumpService.Benchmark.csproj
src/SuperDumpService.Test/SuperDumpService.Test.csproj
src/SuperDumpService/Services/SlackNotificationService.cs
src/SuperDumpService/SuperDumpService.csproj
src/SuperDumpService/web.config
src/SuperDumpTests/SuperDumpTests.csproj

Upgraded more projects to .NET 5 and latest and greatest library versions.

Latest and greatest
